[package]
name = "quickstitch"
version = "1.0.0"
edition = "2024"

[dependencies]
image = { version = "0.25.2", features = ["rayon", "jpeg", "png", "webp"] }
natord = "1.0.9"
rayon = "1.10.0"
thiserror = "1.0.63"
itertools = "0.13.0"

[dev-dependencies]
criterion = "0.5.1"
